### ISSUE TITLE
Use normal markdown parser instead of Simple Markdown

### ISSUE THREAD

**Issue by Davilarek** [Davilarek/MessageLoggerV2-fixed#12]
Current behavior:
![obraz](https://user-images.githubusercontent.com/62715937/233360787-529a8501-7f8e-49b1-99b8-20665b9ebf15.png)
Excepted behavior:
![obraz](https://user-images.githubusercontent.com/62715937/233360870-ffcd74c2-418b-49aa-b816-b7e0814a8737.png)
Code for normal markdown parser:
```js
ZeresPluginLibrary.WebpackModules.getByProps("defaultRules", "parse")
```
Related code:
https://github.com/Davilarek/MessageLoggerV2-fixed/blob/1be9859643da6cca135da2060d5ac1f6b06a4412/Plugins/MessageLoggerV2/MessageLoggerV2.plugin.js#L3588

**Comment by 32enoki** [comment]
apply this with other new markdowns (e.g. heading text, bulleted lists, hyperlinks, etc)

**Comment by Davilarek** [comment]
These should work on the Simple Markdown
