### ISSUE TITLE
[Feature Request] Notification whitelist and more

### ISSUE THREAD

**Issue by Voleno1** [Davilarek/MessageLoggerV2-fixed#3]
First of all, awesome work, really appreciate it!
Here are a couple of features I'd like to request:
-Notification whitelist: the opposite to notification blacklist in contextmenu (only show notifications for set by user servers). I think it would need like additional setting in settings.
-Always show notifications for selected channel.
-Always show notifications for selected guild.

I think it would make notifications more customizable.

**Comment by Davilarek** [comment]
Please note that this feature is a little complex to implement and may not fully mirror what you wanted.
In case of request to change any of the features, please create a new issue.
