### ISSUE TITLE
Unopmz code

### ISSUE THREAD

**Issue by Hacker1254** [Davilarek/MessageLoggerV2-fixed#6]
you might have some unoptimised code, this is me just hovering over a reaction
you can see spikes in the usage of when i had hoverd over
![image](https://user-images.githubusercontent.com/69991448/230742176-1e53ae62-176c-4f89-8533-49d237a57a00.png)

**Comment by Davilarek** [comment]
Have you tried without ML enabled? Also the "fixing" code is mostly just renaming stuff to work on latest discord, so performance issues probably come from the original code.

**Comment by Hacker1254** [comment]
to be honest i don't know what i was on when i wrote this lmao

Uhm something like this error is likely from BD its self or one of the libs ML is using, my bad for opening this lmao
