### ISSUE TITLE
Bug in DM

### ISSUE THREAD

**Issue by thiaguinho4** [Davilarek/MessageLoggerV2-fixed#8]
When someone deletes the message in DM, the red background doesn't appear, but the context of Remove from log, etc., continues to function.

**Comment by Davilarek** [comment]
I cannot reproduce your issue, Maybe theme/other plugin conflict? 
![obraz](https://user-images.githubusercontent.com/62715937/231791093-94380be8-865c-457c-986d-4217c36e5133.png)

**Comment by thiaguinho4** [comment]
It only happens once, forget it lol
Thank you for your attention
