### ISSUE TITLE
MLV2 failed to start

### ISSUE THREAD

**Issue by Hermivore8151** [Davilarek/MessageLoggerV2-fixed#9]
I have zero idea how any of this works, so here is the preview, this happened right after zerespluginlibary decided to break
![image](https://user-images.githubusercontent.com/130803964/232168568-54a88707-b0c9-4161-b733-324141bae316.png)
apparently zeres broke due to a discord update, so it might be the same cause

**Comment by Davilarek** [comment]
Duplicate of #10
